POST http://localhost:3000/api/v1/shop/register
Content-Type: application/json
x-api-key: "xxxxxx"

{
    "name": "Shop 1",
    "email": "shop1@test.com",
    "password": "password123"
}

###

POST http://localhost:3000/api/v1/shop/login
Content-Type: application/json
x-api-key: "xxxxxx"

{
    "email": "shop1@test.com",
    "password": "password123"
}

###

POST http://localhost:3000/api/v1/shop/logout
Content-Type: application/json
x-api-key: xxxxxx
x-client-id: 696d9f0e016570060e1351f5
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZkOWYwZTAxNjU3MDA2MGUxMzUxZjUiLCJlbWFpbCI6InNob3AxQHRlc3QuY29tIiwiaWF0IjoxNzY4Nzk0NTQwLCJleHAiOjE3Njg5NjczNDB9.lHmeebxkRRi5xKyvqX1KkEokdH9OEzYWG0I9Dl6w0nhEvt_KU7zTOes6MWh0nCOg_GtgUxlia0ATOlcb0JgxUdfmjeWIdaxlCsPJ2KsRsFnClalAr3mA9GtswdN9DBazKJwf3vr0d_RIcmZLrYb9671EFnaVM23OENCCrUpuUyNptOn104GvS7p2aCiPuSzZvvensvtoxMiI_cgSe5BIYeCt6xLS3gWzSlT1kuvMChpzu0w383Vtz37ruGyUX9KrzPMuoVoWCg9GnUMAjUD7QfoB2tvnNV7UJ2qs0lFQTqBOrIy_ErYlBUy-bt7bgcKcsZDlmclJF3JQh1cEO5DGwquCgDuhAtNNF-UV_lsAo_Fp5MpfmFfZb4w5AwJH_EzHO8sfubqAJrapye1Is0KkK4iknrwGFAmvFFWwrH0NVjy04AHZDYTjE31e9S3mYJTkngou46IbzwSljv4IKtrLDuZIyGobBtR-YZpAxPWBsuuoSftNdg3K91rqAxsRVNY6AkSPXVfXi0HaMcPE09dTVsl9orU5w4a0hIXpJWZChuiybijzto8iUIVzoLlg0jJe_1NZtLon4u-g5X67pWDdowRG1XWeig_82Fsrjczi9zHVJKEmIANrhM-oH68m_nnlLqvY-suKlS2oNt7v5itG7odF6DW-WWv0sg_BO58g68g

{}

###

POST http://localhost:3000/api/v1/shop/handleRefreshToken
Content-Type: application/json
x-api-key: xxxxxx
x-client-id: 696d9f0e016570060e1351f5
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZkOWYwZTAxNjU3MDA2MGUxMzUxZjUiLCJlbWFpbCI6InNob3AxQHRlc3QuY29tIiwiaWF0IjoxNzY4ODEzNzk1LCJleHAiOjE3Njg5ODY1OTV9.OWsTbB2oVkpU53hvxKr5tbf1hmMPPcsw-gL-v-kp7fX7urYDfCMd0KkFU8ZWuaZEDxEECcLthvAdSKyvzl3Cl8hiFvsmASz5cQpS80yQsPugSQWxP6TOB-JyqR1PDJXW7miXKIkbv0s02sMDRwMaSEnb4OMWlpboC0Ir5Thr9lgf-FIliPBRwy7aCqX0aHOMMU6ftfP9SnUbmRw14KNXK5Q84SMTAkgCPCSUFL4VYScakVC3fpC-4mlCehF6IqzCrajGg9RtrgbBDtewtrz-qM951R2k5tNi61fh0Jos-kox6DM50h_aXv5qRHVnuLHv5CnrknNBYxuqwqVZJEU0WGaVQVktmuX7z5DpL9-L6pF8kuRnAArN0xgmcu6FhmUYnN13L4R9-XXlr2CZCWXhH_UL-949B-h--EbDS0jdN1YFrMwphG9sJziFr6GF9QP7RuX3tHIIGp50OHaMIoJG9vYm0OQgp2UtmmuBn7NoJiFhryOj_5d7lc8_rghb7mrmLW7W7ad2tU0pvjGtMa-Tyb9WyugOJZooME306UxzipxFwLFFgQP_0xKBRsM_61fXYGdAb5ommzReGW-xxu3kUSbVGJvvOqyCGgnz76rMuJEixDGUKUyPogYVSOi5Ht3Y9up8xzDRtYts2JSN8ushT2LMRsBkm2rkYeniWnshCjI

{
    "refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTZkOWYwZTAxNjU3MDA2MGUxMzUxZjUiLCJlbWFpbCI6InNob3AxQHRlc3QuY29tIiwiaWF0IjoxNzY4ODEzNzk1LCJleHAiOjE3Njk0MTg1OTV9.JZXRTBshpNlTzOzp-fJjH0CHFaq_CkFq-p7l70Ul6z9reVNbtj9kgJkVkDuWtVEguf3MMH728YWWzi93_nTf8ZGRk7JDxD-EsbSVvSJ5P649NcqUeKf-3pNzoNEY4JAO4AfopSxyhlGLY5TRT6WtCl8kJWjfJQOPb-7Nron6k10nU3ROWTmpR311lQkBSanZoXPMXv4tvqNUhQeqhzMSvc2_ZcNerEPN08GOzTFBJHD4WeS-wzxbkOIy2D24tgFd69jqAzqytadNyKtGVxV9MMhoNCMQLBKnFgTaxWoOECXDBQMXgWRFBznFjzcuaz34qThPqpWEz6t7ZGld6WU8HxJboDDQSIgqCmdTurnwNQfifGGI2Kl8Zuun_LlFUJgyFGbg2Dt7jFGvm_ykw9ZCWfoH_t130tSD5maFyfXAJuw0AifYnNluYR-zRPjKLyyXYyzSv3sAXiOzHSX9h_pAvgy_X8c2hRHfY36qa8JF_X8njZkgvdw_d2WU-wDUwSdTk5u0jrLkBLA0_wD2Wv8aC-f420nVNtkIkCiAwsfKDM9zjueb6N7K9273Pg05HL0Pr0Xvsu5w-Zlb6LFGBcx-kYTEABJDMVOtluW15iQEo6zXzdHVWqtmzsRQwVSv1sW4JSDtI0KOQ9_GPJ5HaH14CW7jSWQw2Rg-AMju5obpqPM"
}